주간분석 통계 및 위로 한마디 기능 추가
jellyyelly/bside409 pull request #11
Opened 2024-11-27 04:07 UTC by jonghyeok-97

2024-12-03 18:34 UTC, jellyyelly requested changes
고생 많으셨습니다~

충돌 발생하는 부분 코멘트 남겨놨으니 확인 부탁드리고, 위클리 리포트 생성 부분에 수정 요청한 내용 확인 부탁드립니다 :)

2024-12-03 18:34 UTC, jellyyelly commented on src/test/java/bsise/server/report/daily/repository/DailyReportRepositoryTest.java
> +        System.out.println(dto.getUnPublishedCount()); // createPublishedLetter의 개수
이 부분 Assertions 라이브러리로 수정 요청드립니다~

2024-12-03 18:34 UTC, jellyyelly commented on src/main/java/bsise/server/clova/weekly/ClovaWeeklyReportRequestDto.java
이 파일이 충돌이 발생하는데 `git mv` 명령어로 파일을 이동한 후에 커밋해주시면 충돌해결 될거에요

2024-12-03 18:34 UTC, jellyyelly commented on src/main/java/bsise/server/report/weekly/service/WeeklyReportService.java
> +        WeeklyPublishedStaticsDto staticsDto = dailyReportRepository.findPublishedStatics(oneWeekDates);
- 전체적으로 100줄 가까이 되는 메서드에는 여러 기능들이 붙어있는데, 리팩토링 때 분리가 되면 좋을 것 같습니다.
- line 80~86에 있는 List<Letter>를 사용하면 굳이 DB에 접근해서 개수 세는 쿼리를 안보내도 될 것 같습니다.
  - 검토 한 번 해보시고, 위에서 조회한 List<Letter>를 활용하는 방식으로 리팩토링 해주시면 될 듯 합니다.

```java
// line 80 ~ 86
Map<LocalDate, List<Letter>> latestThreeLettersByDate = latestLettersByDate.entrySet().stream()
                .collect(Collectors.toMap(
                        Entry::getKey,
                        entry -> entry.getValue().stream()
                                .limit(3)
                                .collect(Collectors.toList())
                ));
```

2024-12-05 11:40 UTC, jonghyeok-97 commented on src/test/java/bsise/server/report/daily/repository/DailyReportRepositoryTest.java
> +        System.out.println(dto.getUnPublishedCount()); // createPublishedLetter의 개수
수정 완! 했습니다

2024-12-05 11:40 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/weekly/service/WeeklyReportService.java
> +        WeeklyPublishedStaticsDto staticsDto = dailyReportRepository.findPublishedStatics(oneWeekDates);
보통 통계 같은 복잡한 요구사항이면 Querydsl 이나, MyBatis, JdbcTemplate 사용한다 하더라구요. 이 부분은 학습해서 추후에 리팩토링 하겠습니다.

그리고, line 80~86 부분 이용하려고 고려해봤는데 80~86부분은 일일 분석이 생성되지 않은 부분만 모아둔 거여서, 80~86라인 뿐만 아니라 70~72라인도 써야 하는데 여기서 일일 분석이 이미 된 날짜에서 publised/unpublished 를 구분하기 위한 stream count 가 진행되도록 구현해야 할 것 같더라구요.
```
// 70~72 line 날짜별로 편지들을 3개씩 묶기
        Map<LocalDate, List<Letter>> latestLettersByDate = userLettersByLatest.stream()
                .collect(Collectors.groupingBy(
                        letter -> letter.getCreatedAt().toLocalDate()));
```
그래서, 만약, DB 접근 쿼리를 안하기 위해 일일 분석을 찾는 70~80 line 에서 130 line 에 쓰일 변수를 미리 만드는 게 맞나? 싶기도 하고, 성능이 이슈라면 join 쿼리를 먼저 손 봐야할 것 같은 생각이 듭니다.

결론!
1. 주간 분석에 사용된 쿼리들의 실행계획을 통해 쿼리 개선
2. querydsl / MyBatis / JdbcTemplate 이 왜 통계 쿼리에서 좋은지 학습 후, 주간 통계 서비스 리팩토링
3. publised 개수를 위한 DB 1번 접근을 줄여보기
순으로 진행해보겠습니다!

2024-12-11 02:04 UTC, jellyyelly approved these changes
고생 많으셨습니다!! 👍👍

2024-12-11 02:07 UTC, merged