일일 리포트, F,T 위로 챗봇 프롬프트 개선, letter에 대한 응답 생성 메서드 전략 패턴으로 분리
jellyyelly/bside409 pull request #14
Opened 2024-12-03 17:34 UTC by sharpie1330

#### 일일 리포트
  - 일일 리포트 응답을 개선하기 위해 프롬프트를 변경했습니다.
  - 또한 일일 리포트 생성 시 필요한 요청 메시지 형식을 변경했습니다.

#### letter, reply
  - F, T 위로 챗봇 프롬프트를 악의적인 요청에도 정해진 형식대로의 응답을 하도록 개선했습니다.
  - clova가 잘못된 응답 형식의 메시지 응답 시 reply는 저장되지 않지만, letter는 저장되어 조회 시 예외가 발생하던 문제를 해결했습니다.
    - letter에 대한 응답 생성 메서드를 전략 패턴으로 분리하고, 잘못된 응답 시 letter를 롤백하는 서비스를 구현했습니다.

2024-12-03 19:39 UTC, jellyyelly requested changes
프롬프트 개선과 롤백 전략은 별개의 PR로 올려주시면 프롬프트 개선 부분 먼저 병합할 수 있습니다!
롤백 전략 부분은 조금 더 나은 방법으로 개선하면 좋을 것 같아요

2024-12-03 19:39 UTC, jellyyelly commented on src/main/java/bsise/server/report/daily/service/DailyReportService.java
> +                .collect(Collectors.joining("\n"));
1. `AtomicInteger`를 사용한 이유가 무엇인가요? `primitive`인 int 타입을 사용하지 않는 이유가 있을까요?
2. 구분자에 대해 생각을 해봤는데요, `Letter::getMessage`에서 `,` 또는 `\n` 같은 문자가 들어가면 어떻게 될까요? 테스트가 필요해 보입니다. Dummy를 생성하는 부분에서 `,` 또는 `\n`으로 구분하면 안되겠다는 생각도 드네요 ㅎㅎ

2024-12-03 19:39 UTC, jellyyelly commented on src/main/java/bsise/server/letter/LetterService.java
전략 패턴으로 구현할 때 기존 `LetterService`의 코드를 제거하면 안됩니다. 이 코드를 제거하면 다른 전략(말씀드렸던 임시 저장 후 재생성 전략)은 사용할 코드가 없어지거든요.

2024-12-04 08:01 UTC, sharpie1330 commented on src/main/java/bsise/server/report/daily/service/DailyReportService.java
> +                .collect(Collectors.joining("\n"));
1. 당시 getAndIncrement라는 메서드를 사용하면 순서대로 증가시키기 편리하겠다 생각했고, 왜인지 모르게 멀티스레딩 환경이라고 생각해 적합하다고 생각해 사용했었습니다. 지금 보니 잘못 구현된 부분이네요. 이부분은 primitive 타입으로 수정하겠습니다.
2. 전송 자체는 문제가 없는 것 확인했습니다. 위 코드에서 생성한 formattedMessages를 그대로 본문으로 해 보내게 되니까요. 다만,
```
@Override
    public ClovaResponseDto sendDailyReportRequest(String message) {
        int lettersCount = message.split("\n").length;
        return DummyDailyReportClovaResponseDto.createDummy(lettersCount);
    }
```
이 코드는 말씀하신 대로 수정해야 겠네요!
테스트 코드까지 작성 후 다시 pr하겠습니다.

2024-12-05 10:34 UTC, closed without merging