reply, cache 버그 수정
jellyyelly/bside409 pull request #28
Opened 2024-12-16 10:29 UTC by jellyyelly

2024-12-16 10:34 UTC, sharpie1330 approved these changes
LGTM!

2024-12-16 10:34 UTC, sharpie1330 commented on src/main/java/bsise/server/reply/ReplyService.java
> +    @Transactional(readOnly = true)
👍

2024-12-16 10:34 UTC, sharpie1330 commented on src/main/java/bsise/server/report/retrieve/service/ReportStatusRetrieveService.java
> -            key = "#userId.toString() + #targetDate.toString()", unless = "#result == null || #result.size() == 0"
그냥 userId로 처리하셨군요
굿입니다

2024-12-16 17:01 UTC, sharpie1330 requested changes
src/main/java/bsise/server/report/retrieve/service/ReportStatusRetrieveService.java 의
query를 수정해야 할 것 같아요

```
// 편지 작성일을 weekOfYear 로 변환 후 주간 기준으로 그루핑
        Map<Integer, List<WeeklyReportDto>> reportsByWeekOfYear = dailyReports.stream()
                .collect(groupingBy(report -> report.getLetterCreatedAt().get(WEEK_FIELDS.weekOfWeekBasedYear())));
```

reply가 있는 letter만 dailyReport를 생성 할 수 있게 변경되었기 때문에
dailyReport 생성 가능 여부 조회 또한 reply가 있는 letter 기준으로 로직이 변경되어야 할 것 같습니다.

이 부분을 놓쳤었네요...

2024-12-17 05:37 UTC, jellyyelly commented
> src/main/java/bsise/server/report/retrieve/service/ReportStatusRetrieveService.java 의 query를 수정해야 할 것 같아요
> 
> ```
> // 편지 작성일을 weekOfYear 로 변환 후 주간 기준으로 그루핑
>         Map<Integer, List<WeeklyReportDto>> reportsByWeekOfYear = dailyReports.stream()
>                 .collect(groupingBy(report -> report.getLetterCreatedAt().get(WEEK_FIELDS.weekOfWeekBasedYear())));
> ```
> 
> reply가 있는 letter만 dailyReport를 생성 할 수 있게 변경되었기 때문에 dailyReport 생성 가능 여부 조회 또한 reply가 있는 letter 기준으로 로직이 변경되어야 할 것 같습니다.
> 
> 이 부분을 놓쳤었네요...

모든 서비스에서 Letter 테이블을 조회할 때 Reply랑 inner join을 반드시 해야하는 제약 조건이 있는거나 마찬가지네요..?
우선 수정하고 병합 시켜놓을게요 👍

2024-12-17 06:33 UTC, sharpie1330 approved these changes

2024-12-17 06:33 UTC, sharpie1330 commented on src/main/java/bsise/server/letter/LetterRepository.java
> +                JOIN reply r ON l.letter_id = r.letter_id
👏

2024-12-17 12:09 UTC, merged