주간분석 생성 및 주간분석 조회 API 추가
jellyyelly/bside409 pull request #6
Opened 2024-11-19 05:03 UTC by jonghyeok-97

#### 주간분석 프로세스
1.  일일 분석 생성 및 저장
    - 일일분석이 없는 편지를 찾아서 날짜별로 최신순으로 3개씩 그룹화한다.
    - 3개씩 그룹화된 편지들을 Clova 에게 일일분석을 만들도록 요청한다.
    - Clova API 응답을 가공하여 일일분석 저장 및 편지 분석 저장

2. 주간분석 생성
     - 주간분석 받을 날짜에 해당하는 일일분석들의 설명과 감정을 찾는다.
     - 설명과 감정을 Clova 에게 주간분석에 필요한 감정별 추이와 위로 한마디를 요청한다.
     -  Clova API 응답을 가공하여 주간분석 저장한다.

* 참고사항
    - 프로세스를 한 눈에 읽기 위해서 메서드 분리를 하지 않음. `1. 일일분석 생성 및 저장에서` 일일분석 API 를 사용하고있기 때문에 같이 리팩토링해야 함.
    - 현재는 트랜잭션 1개에 주간분석 프로세스가 모두 묶여있음
        - 1번과 2번을 트랜잭션 전파 속성 REQUIRED_NEW 를 사용해서 둘을 분리할 수 있을 것 같음

#### etc
- WeekFields 관련 테스트 추가
- WeeklyReport 에 `weeklyName` 을 빼고, weekOfYear 와 startDate endDate 를 추가
    - weeklyName 은 view 요구사항이라서, 엔티티에는 맞지않다고 판단
-  주간분석 조회 API 의 Request Body 에 userId 를 받는데, 이를 언제 사용하는지 잘 모르겠어서 제외함
- 주간분석 조회 API 수정
    - `/weekly?week=42` -> `/weekly?startDate=2024-11-15&endDate=2024-11-21`

2024-11-19 11:30 UTC, sharpie1330 approved these changes
수고하셨습니다~👍🤗

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportController.java
> +    @ResponseStatus(HttpStatus.OK)
CREATED로 통일하면 좋을 것 같습니다

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +                ));
현재 "일일 리포트가 없는 편지를 조회 -> 날짜별 최신 편지들을 최대 3개씩 묶기" 인데, 이것보다 "일일 리포트가 없는 날짜를 조회 -> 해당 날짜의 편지 최대 세개씩 조회해 묶기" 방식은 어떠세요?
사용되지 않을 수도 있는 Letter를 조회해오는 게 좋을 지 잘 모르겠어요

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +                ));
주간 분석의 경우 `일일 리포트 생성 -> 주간 리포트 생성`이니까 만약 일일 리포트 생성 내역이 아예 없으면 최대 7개까지 일일 리포트를 생성하고 주간 리포트 생성까지 해야 하는데요. 매우 오랜 시간이 소요될 것 같아서 비동기로 처리할 방법을 고민해보는 것도 좋을 것 같아요

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +        List<LocalDate> oneWeekDates = createOneWeek(weeklyReportRequestDto.getStartDate());
이름이 약간 헷갈려서 getOnWeek는 어떤지 제안이요~

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +                .collect(Collectors.joining());
joining할 때 아무 조건 없는데 이렇게 되면
`슬픔, 기쁨, 두려움`이 있다고 할 때 `슬픔기쁨두려움` 이렇게 입력되지 않을까요?

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +        ClovaResponseDto clovaResponseDto = clovaService.sendWeeklyReport(
sendWeeklyReport는 주간리포트를 전송한다는 의미 같아서 `sendWeeklyReportRequest`는 어떨지... ㅎㅎ

2024-11-19 11:30 UTC, sharpie1330 commented on src/main/java/bsise/server/report/weekly/dto/WeeklyReportRequestDto.java
> +    private final LocalDate startDate;
가능한 날짜인지 확인하는 부분은 @jellyyelly가 구현하셔서 검증 안해도 될까요?

2024-11-19 13:12 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/ReportService.java
> +                ));
맞아여 리팩토리이 시급합니다ㅋㅋㅋㅠㅠ

2024-11-19 13:14 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/ReportService.java
> +        List<LocalDate> oneWeekDates = createOneWeek(weeklyReportRequestDto.getStartDate());
1일 -> 7일로 만든다는 의미에서 create 로 했슴다! get은 이미 뭔가 있는 것에서 가져온다는 느낌이어서요👍

2024-11-19 13:15 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/ReportService.java
> +                .collect(Collectors.joining());
고쳐야겠습니다..ㅎ

2024-11-19 13:24 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/ReportService.java
> +                ));
letterRepository의 `findLettersByDailyReportIsNullAndUserIdAndCreatedAtBetween` 를 @Query 로 수정해서 최대 3개만 퍼올리도록 수정하겠습니다!

2024-11-19 13:31 UTC, jonghyeok-97 commented on src/main/java/bsise/server/report/weekly/dto/WeeklyReportRequestDto.java
> +    private final LocalDate startDate;
추가하겠습니다!

2024-11-20 07:59 UTC, jellyyelly requested changes
트랜잭션 전파까지 고려하시고.. 데일리 리포트도 고려해야해서 가장 복잡한 작업이셨을거라 생각됩니다..
고생하셨습니다! 👍

주간 리포트 생성 시 수정이 필요한 부분이 있습니다. 리뷰 확인 부탁드려요!

2024-11-20 07:59 UTC, jellyyelly commented on src/main/java/bsise/server/clovar/DailyReportExtractor.java
> +//    public static
주간 분석 결과 파싱 부분이 빠진 것 같은데, 확인 부탁드려요!

2024-11-20 07:59 UTC, jellyyelly commented on src/main/java/bsise/server/report/ReportService.java
> +                .orElseThrow(() -> new NoSuchElementException("주간분석이 존재하지 않습니다"));
RestControllerAdvice 관련해서 `NoSuchElementException` 대신 `EntityNotFoundException`를 상속한 별도의 예외로 변경 부탁드립니다!

2024-11-20 07:59 UTC, jellyyelly commented on src/main/java/bsise/server/common/RestApiControllerAdvice.java
> +
일반적으로 `NoSuchElementException` 예외는 컬렉션이나 iterator 등에서 요소가 없을 때 발생하는 예외로 알고있는데요,
보통 이 부분은 클라이언트 잘못이면 404, 서버 측 잘못이면 500 에러로 응답하는데요,
해당 예외가 언제 발생하는지 코드를 살펴보니, `WeeklyReport` 엔티티를 못찾을 때 발생시키도록 의도하셨더라구요.

이 프로젝트에선 찾고자 하는 엔티티가 없을 때 `EntityNotFoundException` 예외를 발생시켜 최종적으로 404 Not Found 를 응답하도록 의도했습니다. 작성하신 핸들러는 이 프로젝트에서 사용되지 않을 것 같습니다..

2024-11-20 07:59 UTC, jellyyelly commented on src/main/java/bsise/server/report/ReportService.java
> +        );
`letterRepository.findThreeLettersWithoutDailyReport(...)` 쿼리를 보면 `daily_report_id IS NULL` 을 조건으로 필터링을 한다음, `LIMIT 3`을 수행하는데요. 이 부분에 문제가 있어보입니다.
아래 예시를 들어서 설명해 볼게요.

`월요일부터 토요일까지` 하루에 20건씩 6일간 작성한 사용자가 있고, 월요일날 편지를 10건쯤 작성했을 때 `데일리 리포트`를 생성한 사용자가 있다고 가정해 볼게요.

만약 `일요일` 아무 떄에 `letterRepository.findThreeLettersWithoutDailyReport(...)`를 호출하면, 월요일에 가장 마지막에 작성한 편지 3개만 조회됩니다. 그리고 월요일은 데일리 리포트가 이미 생성한 날입니다.

쿼리의 LIMIT 3 부분 떄문에 발생하는 문제인데, 쿼리 자체에서 해결하거나 Java 로 처리하셔야 할 것 같아요.

2024-11-20 07:59 UTC, jellyyelly commented on src/main/java/bsise/server/report/ReportService.java
> +                        entry -> buildDailyReport(LocalDate.now(), entry.getKey()),
`buildDailyReport`의 첫 번째 인자는 `targetDate`가 들어가야 하는 것으로 알고있는데, `LocalDate.now()`로 하면 생성되는 모든 `DailyReport`는 targetDate가 메서드를 호출한 현재 날짜가 되버리는 문제가 있어보여요.

2024-11-20 08:07 UTC, sharpie1330 commented on src/main/java/bsise/server/clovar/DailyReportExtractor.java
> +//    public static
현재 주간분석 clova api 요청 부분도 구현 안되어 있는데 이부분도 완성하고 병합해야 할까요? 아니면 일단 임시로 clova api 요청 대체하는 클래스 만들기로 했으니까 나중에 구현하는 걸로 해도 되려나요?

2024-11-20 08:11 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +                        entry -> buildDailyReport(LocalDate.now(), entry.getKey()),
그렇네요 저도 리뷰하면서 이부분을 놓쳤군요...!
말씀하신대로 targetDate가 들어가야 합니다.

2024-11-20 08:24 UTC, jellyyelly commented on src/main/java/bsise/server/clovar/DailyReportExtractor.java
> +//    public static
기획 부분에서 확정이 안된 부분이라 빼고 진행한거였군요
저는 확정된 부분만 가지고 가는 줄 알고있었어요

2024-11-20 08:26 UTC, sharpie1330 commented on src/main/java/bsise/server/report/ReportService.java
> +        );
이부분은 저도 알아차리지 못했네요 👍👍

2024-11-20 12:45 UTC, jellyyelly approved these changes
고생 많으셨습니다~!

2024-11-21 08:01 UTC, merged